import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Banner from "../components/Banner";
import Sidebar from "../components/Sidebar";
import Work from "../components/Work";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Sidebar />
        <div className="h-[65vh] lg:h-[80vh]">
          <Banner />
        </div>
        <Work />
        <About />
      </div>
    </div>
  );
};

export default Home;
